version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    container_name: booking-project
    environment:
      POSTGRES_DB: booking-project-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'


