version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    container_name: booking-project-db
    environment:
      POSTGRES_DB: booking-project-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - bookingProjectNetwork

  bookingproject:
    image: 'bookingproject:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookingproject
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/booking-project-db
    depends_on:
      - db
    networks:
      - bookingProjectNetwork

networks:
  bookingProjectNetwork:


